site_name: unlimited_reagents 2018 Writeups


pages:
- Home: 'README.md'
- PACTF 2018:
        - 'Lovelace': 'PACTF-2018/lovelace/README.md'
                - 'Let Me In': 'PACTF-2018/lovelace/let-me-in/README.md'
                - 'Credit Card Leak': 'PACTF-2018/lovelace/credit-card-leak/README.md'
                - 'Go Git It': 'PACTF-2018/lovelace/go-git-it/README.md'
                - 'Open Sourcery 2018': 'PACTF-2018/lovelace/open-sourcery-2018/README.md'
                - 'Third Eye': 'PACTF-2018/lovelace/third-eye/README.md'
                - 'Who Said It?': 'PACTF-2018/lovelace/who-said-it/README.md'
