site_name: unlimited_reagents 2018 Writeups

pages:
- Home: 'index.md'
- PACTF 2018:
        - 'Lovelace':
                - 'Overview': 'PACTF-2018/lovelace/README.md'
                - 'A Picture is a Thousand Words (10 points)': 'PACTF-2018/lovelace/a-picture-is-a-thousand-words/README.md'
                - 'Straight From The Emperor (10 points)': 'PACTF-2018/lovelace/straight-emperor/README.md'
                - 'Caesar Cipher? (20 points)': 'PACTF-2018/lovelace/caesar-cipher/README.md'
                - 'Let Me In (20 points)': 'PACTF-2018/lovelace/let-me-in/README.md'
                - 'Go Git It (25 points)': 'PACTF-2018/lovelace/go-git-it/README.md'
                - 'Who Said It? (25 points)': 'PACTF-2018/lovelace/who-said-it/README.md'
                - 'Bad Melody (30 points)': 'PACTF-2018/lovelace/bad-melody/README.md'
                - 'Open Sourcery 2018 (30 points)': 'PACTF-2018/lovelace/open-sourcery-2018/README.md'
                - 'Credit Card Leak (35 points)': 'PACTF-2018/lovelace/credit-card-leak/README.md'
                - 'Third Eye (40 points)': 'PACTF-2018/lovelace/third-eye/README.md'
                - 'Getting to Know GDB (50 points)': 'PACTF-2018/lovelace/getting-to-know-gdb/README.md'
                - 'Security Through Obscurity (50 points)': 'PACTF-2018/lovelace/security-obscurity/README.md'
                - 'Beats by Dr. K (55 points)': 'PACTF-2018/lovelace/beats-by-dr-k/README.md'
                - 'The Lottery, Part Two: Untwisting Fate! (90 points)': 'PACTF-2018/lovelace/lottery-part-2/README.md'
                - 'Siblings (120 Points)': 'PACTF-2018/lovelace/siblings/README.md'
        - 'Hopper':
                - 'Overview': 'PACTF-2018/hopper/README.md'
- picoCTF 2018:
        - 'be-quick-or-be-dead-3 (350 points)': 'PICOCTF-2018/be-quick-or-be-dead-3/README.md'
        - 'James Brahm Returns (700 points)': 'PICOCTF-2018/james-brahm-returns/README.md'
        - 'circuit123 (800 points)': 'PICOCTF-2018/circuit123/README.md'
        - 'Dog or Frog (900 points)': 'PICOCTF-2018/dog-or-frog/README.md'
